name: Brokli Link Checker
description:
  Check for broken links in static sites before deployment using brokli CLI
author: EndlessTrax

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: link
  color: blue

# Define your inputs here.
inputs:
  generator:
    description: Static site generator to use (e.g., 'hugo')
    required: true
  drafts:
    description: Include draft posts when checking links
    required: false
    default: 'false'
  port:
    description: Override default port for the static site server
    required: false
    default: ''

# Define your outputs here.
outputs:
  result:
    description: Result of the broken link check

runs:
  using: node24
  main: dist/index.js
